spring.application.name=java-order-management-service
spring.datasource.url=jdbc:sqlite:../db/ecommerce-db.sqlite3
spring.datasource.driver-class-name=org.sqlite.JDBC
spring.jpa.database-platform=org.hibernate.community.dialect.SQLiteDialect
spring.jpa.hibernate.ddl-auto=update
spring.server.port=8082