spring.application.name=java-order-management-service
spring.datasource.url=jdbc:sqlite:../db/ecommerce-db.sqlite3
spring.datasource.driver-class-name=org.sqlite.JDBC
spring.jpa.database-platform=org.hibernate.community.dialect.SQLiteDialect
spring.jpa.hibernate.ddl-auto=update
server.port=8082
spring.security.user.name=admin
spring.security.user.password=admin
spring.security.user.roles=ADMIN
spring.main.allow-bean-definition-overriding=true
spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.security.servlet.SecurityAutoConfiguration